# Generated by Django 4.0 on 2021-12-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(As per PAN Card)', max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('current_address', models.CharField(max_length=40)),
                ('pincode', models.CharField(max_length=6)),
                ('loan_amount_needed', models.CharField(max_length=8)),
                ('annual_turnover', models.CharField(max_length=10)),
                ('number_of_ITR', models.IntegerField(help_text='(Number of years ITR available for)')),
                ('business_registration', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='YES', max_length=3)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homeloan',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('salaried', models.BooleanField(max_length=10)),
                ('self_employed', models.BooleanField(default=False)),
                ('net_monthly_income', models.CharField(max_length=10)),
                ('annual_turnover', models.CharField(max_length=10)),
                ('number_of_ITR', models.IntegerField(help_text='(Number of years ITR available for)')),
                ('address', models.CharField(help_text='(Your current address)', max_length=40)),
                ('pincode', models.CharField(max_length=6)),
                ('property_market_value', models.CharField(max_length=8)),
                ('loan_amount_needed', models.CharField(max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Homeloantransfer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.CharField(help_text='(Your current address)', max_length=40)),
                ('pincode', models.CharField(max_length=6)),
                ('self_employed', models.BooleanField(default=False)),
                ('annual_profit', models.CharField(help_text='(As per ITR)', max_length=10)),
                ('existing_loan', models.CharField(blank=True, help_text='(Existing loan if any)', max_length=30)),
                ('current_outstanding', models.CharField(blank=True, help_text='(Current loan outstanding(bank deatils) if any)', max_length=10)),
                ('salaried', models.BooleanField(max_length=10)),
                ('net_monthly_income', models.CharField(max_length=10)),
                ('topup_required', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='NO', max_length=3)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoanAgainstProperty',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('salaried', models.BooleanField(max_length=10)),
                ('self_employed', models.BooleanField(default=False)),
                ('net_monthly_income', models.CharField(max_length=10)),
                ('annual_turnover', models.CharField(max_length=10)),
                ('number_of_ITR', models.IntegerField(help_text='(Number of years ITR available for)')),
                ('address', models.CharField(help_text='(Your current address)', max_length=40)),
                ('pincode', models.CharField(max_length=6)),
                ('property_market_value', models.CharField(max_length=8)),
                ('loan_amount_needed', models.CharField(max_length=8)),
                ('property_type', models.CharField(choices=[('residential', 'RESIDENTIAL'), ('commercial', 'COMMERCIAL'), ('industrial', 'INDUSTRIAL')], default='commercial', help_text='(Choose any)', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('net_monthly_income', models.CharField(max_length=8)),
                ('job_type', models.CharField(choices=[('private', 'PRIVATE'), ('goverment', 'GOVERMENT')], default='private', max_length=10)),
                ('bank_name', models.CharField(help_text='(Salary account bank name)', max_length=30)),
                ('emi', models.CharField(help_text='(EMI if any)', max_length=10)),
                ('experience', models.IntegerField(help_text='(Total working experience)')),
                ('loan_amount_needed', models.CharField(max_length=7)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.CharField(help_text='(Your current address)', max_length=50)),
                ('query', models.TextField(help_text='(Enter yoyr query', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
            ],
        ),
    ]
